website:
  - match: ["*.html", "*.js", "*.css"]
    exlude: ["!./github/*", "!readme.md"]

cicd:
  - match: ".github/*"
    exlude: ["*.html", "*.js", "*.css"]

fix:
  - branch: "patch/*"

feature:
  - branch: "feature/*"
