name: "Pull Request Labeler"
on:
  pull_request_target:
    types: [opened, synchronize]
  pull_request:
    types: [opened]

jobs:
  triage:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.TOKEN_GITHUB }}"

  label_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Label PRs
        if: github.event.action == 'opened' # Only run the action when the PR was first opened
        uses: ffittschen/pr-branch-labeler@v1
        with:
          repo-token: ${{ secrets.TOKEN_GITHUB }}
